name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (runs in UTC)
  workflow_dispatch:

run-name: Keep Alive — ${{ steps.time.outputs.ist }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Get Indian Time
        id: time
        run: echo "ist=$(TZ=Asia/Kolkata date '+%d-%b-%Y %H:%M:%S IST')" >> $GITHUB_OUTPUT

      - name: Show Indian Time
        run: |
          echo "Run started at (UTC): $(date -u)"
          echo "Run started at (IST): $(TZ=Asia/Kolkata date)"

      - name: Curl request
        run: |
          echo "Pinging backend..."
          curl -s https://vit-voice-sadhana.onrender.com || true
