name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (runs in UTC)
  workflow_dispatch:        # lets you run it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -s https://vit-voice-sadhana.onrender.com || true
