name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (runs in UTC)
  workflow_dispatch:        # lets you run it manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request with timestamp
        run: |
          echo "=== Ping started at $(date -u) UTC ==="
          curl -i https://vit-voice-sadhana.onrender.com || true
          echo "=== Ping finished at $(date -u) UTC ==="
